import typing

"""Valid strings to pass to keyboard_action and hold_keyboard_action"""
KEYBOARD_KEYS = typing.Literal[
    "\t",
    "\n",
    "\r",
    " ",
    "!",
    '"',
    "#",
    "$",
    "%",
    "&",
    "'",
    "(",
    ")",
    "*",
    "+",
    ",",
    "-",
    ".",
    "/",
    "0",
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    ":",
    ";",
    "<",
    "=",
    ">",
    "?",
    "@",
    "[",
    "\\",
    "]",
    "^",
    "_",
    "`",
    "a",
    "b",
    "c",
    "d",
    "e",
    "f",
    "g",
    "h",
    "i",
    "j",
    "k",
    "l",
    "m",
    "n",
    "o",
    "p",
    "q",
    "r",
    "s",
    "t",
    "u",
    "v",
    "w",
    "x",
    "y",
    "z",
    "{",
    "|",
    "}",
    "~",
    "accept",
    "add",
    "alt",
    "altleft",
    "altright",
    "apps",
    "backspace",
    "browserback",
    "browserfavorites",
    "browserforward",
    "browserhome",
    "browserrefresh",
    "browsersearch",
    "browserstop",
    "capslock",
    "clear",
    "convert",
    "ctrl",
    "ctrlleft",
    "ctrlright",
    "decimal",
    "del",
    "delete",
    "divide",
    "down",
    "end",
    "enter",
    "esc",
    "escape",
    "execute",
    "f1",
    "f10",
    "f11",
    "f12",
    "f13",
    "f14",
    "f15",
    "f16",
    "f17",
    "f18",
    "f19",
    "f2",
    "f20",
    "f21",
    "f22",
    "f23",
    "f24",
    "f3",
    "f4",
    "f5",
    "f6",
    "f7",
    "f8",
    "f9",
    "final",
    "fn",
    "hanguel",
    "hangul",
    "hanja",
    "help",
    "home",
    "insert",
    "junja",
    "kana",
    "kanji",
    "launchapp1",
    "launchapp2",
    "launchmail",
    "launchmediaselect",
    "left",
    "modechange",
    "multiply",
    "nexttrack",
    "nonconvert",
    "num0",
    "num1",
    "num2",
    "num3",
    "num4",
    "num5",
    "num6",
    "num7",
    "num8",
    "num9",
    "numlock",
    "pagedown",
    "pageup",
    "pause",
    "pgdn",
    "pgup",
    "playpause",
    "prevtrack",
    "print",
    "printscreen",
    "prntscrn",
    "prtsc",
    "prtscr",
    "return",
    "right",
    "scrolllock",
    "select",
    "separator",
    "shift",
    "shiftleft",
    "shiftright",
    "sleep",
    "space",
    "stop",
    "subtract",
    "tab",
    "up",
    "volumedown",
    "volumemute",
    "volumeup",
    "win",
    "winleft",
    "winright",
    "yen",
    "command",
    "option",
    "optionleft",
    "optionright",
]


WALK_FORWARD_DIRECTIONS = typing.Literal["f", "fw", "forward", "forwards"]
WALK_BACK_DIRECTIONS = typing.Literal["b", "bw", "back", "backward", "backwards"]
WALK_LEFT_DIRECTIONS = typing.Literal["l", "left"]
WALK_RIGHT_DIRECTIONS = typing.Literal["r", "right"]

"""Valid strings to pass to walk"""
WALK_DIRECTIONS = (
    WALK_FORWARD_DIRECTIONS
    | WALK_BACK_DIRECTIONS
    | WALK_LEFT_DIRECTIONS
    | WALK_RIGHT_DIRECTIONS
)


UI_NAVIGATE_UP_DIRECTIONS = typing.Literal["up", "u"]
UI_NAVIGATE_LEFT_DIRECTIONS = typing.Literal["left", "l"]
UI_NAVIGATE_RIGHT_DIRECTIONS = typing.Literal["right", "r"]
UI_NAVIGATE_DOWN_DIRECTIONS = typing.Literal["down", "d"]

"""Valid strings to pass to ui_navigate"""
UI_NAVIGATE_DIRECTIONS = (
    UI_NAVIGATE_UP_DIRECTIONS
    | UI_NAVIGATE_LEFT_DIRECTIONS
    | UI_NAVIGATE_RIGHT_DIRECTIONS
    | UI_NAVIGATE_DOWN_DIRECTIONS
)

__all__ = [
    "KEYBOARD_KEYS",
    "WALK_DIRECTIONS",
    "UI_NAVIGATE_DIRECTIONS",
]
