version: "2"

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.13"
  jobs:
    install:
      - pip install --upgrade pip==25.1
      - pip install . --group docs

sphinx:
  configuration: docs/source/conf.py
